#!/bin/sh
# =============================================================================
# docker-entrypoint.sh
#
# cz-js-1058 FIX: ECS Fargate SSM Parameter Store runtime environment
# injection for jQuery/React applications.
#
# This script runs at container startup BEFORE nginx is launched.
# It writes /usr/share/nginx/html/config.js using environment variables
# that ECS Fargate injects from AWS SSM Parameter Store path hierarchies
# defined in the task definition "secrets" array.
#
# SSM Parameter Store hierarchy layout (per environment):
#   /app/dev/api-url              → API_URL
#   /app/dev/feature-flag         → FEATURE_FLAG
#   /app/staging/api-url          → API_URL
#   /app/staging/feature-flag     → FEATURE_FLAG
#   /app/production/api-url       → API_URL
#   /app/production/feature-flag  → FEATURE_FLAG
#
# ECS Fargate task definition "secrets" array snippet (reference only):
#   "secrets": [
#     {
#       "name": "API_URL",
#       "valueFrom": "arn:aws:ssm:<region>:<account>:parameter/app/production/api-url"
#     },
#     {
#       "name": "FEATURE_FLAG",
#       "valueFrom": "arn:aws:ssm:<region>:<account>:parameter/app/production/feature-flag"
#     }
#   ]
#
# For staging, swap the SSM paths to /app/staging/... — the same immutable
# Docker image is reused across all environments without rebuilding.
#
# This approach ensures:
#   - No environment-specific values are baked into the Docker image.
#   - The same immutable image is promoted across dev / staging / production.
#   - Secrets are never stored in image layer history or source control.
#   - Per-environment config is managed exclusively via SSM Parameter Store
#     hierarchies, enabling centralised audit, rotation, and access control.
#
# Required ECS task definition environment / secret references:
#   API_URL       – base URL for the backend API
#                   (SSM path: /app/<env>/api-url)
#   FEATURE_FLAG  – feature flag value for the application
#                   (SSM path: /app/<env>/feature-flag)
#   FEATURE_FLAGS – comma-separated feature flag overrides (optional)
#
# The generated config.js is loaded by index.html before the application
# bundle and populates window.__ENV__ so the jQuery/React app can read
# runtime configuration without any build-time REACT_APP_* variables.
# =============================================================================

set -e

CONFIG_FILE="/usr/share/nginx/html/config.js"

echo "Generating runtime config from ECS Fargate SSM Parameter Store injection..."

cat > "${CONFIG_FILE}" <<EOF
// =============================================================================
// Runtime configuration injected by ECS Fargate at container startup.
// Values are sourced from AWS SSM Parameter Store path hierarchies.
// DO NOT edit this file manually — it is overwritten on every container start.
//
// cz-js-1058 remediation: no build-time REACT_APP_* variables used.
// All values arrive via SSM Parameter Store -> ECS Fargate secrets injection.
// =============================================================================
(function () {
  if (typeof window !== 'undefined') {
    window.__ENV__ = {
      API_URL:       "${API_URL:-}",       // SSM: /app/<env>/api-url
      FEATURE_FLAG:  "${FEATURE_FLAG:-}",  // SSM: /app/<env>/feature-flag
      FEATURE_FLAGS: "${FEATURE_FLAGS:-}"  // SSM: /app/<env>/feature-flags (optional)
    };
  }
})();
EOF

echo "Runtime config written to ${CONFIG_FILE}"

# Hand off to the CMD (nginx)
exec "$@"
